name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:

  copilot-setup-steps:
    runs-on: "ubuntu-latest"

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    - name: Set up Python 3.9 and 3.11
      uses: actions/setup-python@v5
      with:
        python-version: |
          3.9
          3.11

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        # cache0 makes it easy to bust the cache if needed
        gha-cache-key: cache1-test-py3.11-pants2.24
        named-caches-hash: ${{ hashFiles('pants-plugins/*.lock') }}

    - name: Test everything
      run: |
        ./get-pants.sh
        sudo sh -c 'echo "runner:100000:65536" > /etc/subuid'
        sudo sh -c 'echo "runner:100000:65536" > /etc/subgid'
